---
# file: grafana/tasks/main.yml
#
# tasks file
#
- name: ensure grafana is installed
  pacman: name=grafana state=installed
  become: yes
  tags: installation

- name: ensure integrity of grafana configuration
  template:
    src=files/grafana.ini
    dest="/etc/grafana.ini"
    mode=0777
  become: yes
  notify: restart grafana
  tags: configuration

- name: ensure grafana is running and enabled to start on boot
  service:
    name=grafana
    state=started
    enabled=yes
  become: yes
  tags: service
