---
- 
    hosts: all
    tasks:
    - name: install netadata
      pacman: name=netdata state=installed
      become: yes

    - name: install nvidia
      pacman: name=nvidia state=installed
      become: yes

    - name: enable and start netdata service
      systemd:
        name: netdata
        enabled: yes
        state: started
      become: yes

    - name: Create ethminer dir
      file:
        path: ~/ethminer
        state: directory

    - name: download and extract ethminer
      unarchive:
        src: https://github.com/ethereum-mining/ethminer/releases/download/v0.11.0rc1/ethminer-0.11.0rc1-Linux.tar.gz
        dest: ~/ethminer
        remote_src: True
