---
- name: Setup Ethminer
  hosts: miners
  roles:
    - ethminer

- name: Setup Monitoring
  become: true
  hosts: prometheus
  roles:
    - prometheus
    - grafana
    - nginx

# - name: Reboot the server
#   shell: sleep 2 && shutdown -r now "Reboot after installation"
#   async: 1
#   poll: 0
#   become: yes

# - name: Wait for the server
#   local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=10 timeout=120
