- name: Install base packages
  pacman: name=htop,vim,netdata,nvidia,cuda,libcurl-compat,opencl-headers,python-pip state=installed
  become: yes

- name: Install Python packages
  pip:
    name: prometheus_client,nvidia-ml-py3 
    executable: pip3
  become: yes

- name: Enable and start netdata service
  systemd:
    name: netdata
    enabled: yes
    state: started
  become: yes

- name: Nvidia Prometheus exporter
  git:
    repo: 'https://github.com/atomic-coders/nvidia-exporter.git'
    dest: ~/nvidia-exporter
    clone: yes
    update: yes

- name: Copy Nvidia Exporter service
  template:
    src: templates/nvidia-exporter.service.j2
    dest: /etc/systemd/user/nvidia-exporter.service
  become: yes

- name: Enable and start Nvidia Exporter service
  systemd:
    name: nvidia-exporter
    enabled: yes
    state: started
    user: yes
    daemon_reload: yes

- name: Create ethminer dir
  file:
    path: ~/ethminer
    state: directory

- name: Download ethminer
  get_url:
    url: https://github.com/ethereum-mining/ethminer/releases/download/v0.11.0/ethminer-0.11.0-Linux.tar.gz
    dest: ~/ethminer/ethminer.tar.gz
    checksum: sha256:b4219dd45d602430b062cc830d2bc6fa065ab82bdbbc43f3deb165cc7001143b

- name: Extract ethminer
  unarchive:
    src: ~/ethminer/ethminer.tar.gz
    dest: ~/ethminer
    remote_src: True

- name: Copy start ethminer script
  template:
    src: templates/start-ethminer.sh.j2
    mode: 0777
    dest: ~/start-ethminer.sh

- name: Copy ethminer service
  template:
    src: templates/ethminer.service.j2
    dest: /etc/systemd/user/ethminer.service
  become: yes

- name: Loginctl config
  become: yes
  command: sudo loginctl enable-linger {{username}}

- name: Enable and start ethminer service
  systemd:
    name: ethminer
    enabled: yes
    state: started
    user: yes
    daemon_reload: yes
