---
# file: handlers/main.yml
#

- name: restart prometheus
  systemd: name=prometheus state=restarted
  when: prometheus_use_service|bool

- name: reload prometheus
  systemd: name=prometheus state=reloaded
  when: prometheus_use_service|bool

- name: stop prometheus
  systemd: name=prometheus state=stopped
  when: prometheus_use_service|bool



- name: restart node_exporter
  systemd: name=node_exporter state=restarted

- name: reload node_exporter
  systemd: name=node_exporter state=reloaded

- name: stop node_exporter
  systemd: name=node_exporter state=stopped



- name: restart alertmanager
  systemd: name=alertmanager state=restarted
  when: prometheus_use_service|bool

- name: reload alertmanager
  systemd: name=alertmanager state=reloaded
  when: prometheus_use_service|bool

- name: stop alertmanager
  systemd: name=alertmanager state=stopped
  when: prometheus_use_service|bool
